theme: minima
title: Tanner B Remote Pilot
author: Tannerpace
email: tannerpace@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you will find out what it takes to be a professional drone pilot, I will guide you along the way. 
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: @boyashaka83
github_username:  tannerpace
show_excerpts: true # set to false to remove excerpts on the homepage
