theme: jekyll-theme-minimal
title: Tanner B Remote Pilot
author: Tannerpace
email: tannerpace@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
Tanner Bleakley is a FRA Certified Conductor. FAA Certified Unmanned Aerial Vehicle Pilot.
twitter_username: boyashaka83
github_username:  tannerpace
Youtube_username: pedhead
show_excerpts: true # set to false to remove excerpts on the homepage
